# Generated by Django 3.0.5 on 2020-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
